version: '3'

services:
    api:
        build: ./MititBack/
        container_name: mitit_back
        ports:
            - '8082:8081'
        expose:
            - '8082'
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_NAME: ${MYSQL_NAME}
            MYSQL_USERNAME: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            SFTP_HOST: ${SFTP_HOST}
            SFTP_PORT: ${SFTP_PORT}
            SFTP_USERNAME: ${SFTP_USERNAME}
            SFTP_PASSWORD: ${SFTP_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
            JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
            SERVER_PORT: ${SERVER_PORT}
        volumes:
            - api:/home/mitit-back/logs/
        restart: always

    web:
        build: ./MititFront/
        container_name: mitit_front
        ports:
            - '80:80'
        expose:
            - '80'
        depends_on:
            - 'api'
        restart: always

    web-admin:
        build: ./MititAdminFront/
        container_name: mitit_admin_front
        ports:
            - '3000:80'
        expose:
            - '3000'
        depends_on:
            - 'api'
        restart: always

volumes:
    api:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./logs/
